skip_branch_with_pr: true

branches:
  only:
    - master

image: Visual Studio 2017

init:
  - git config --global core.autocrlf true
  - choco install dotnetcore-sdk
  - dotnet --version

before_build:
  - appveyor-retry dotnet restore

build:
  project: MessWala.sln

#test: on

#test_script:
  #- ps: .\run-tests.ps1

deploy: off
